import time

from Utilities.mbedRPC import *

#serdev = '/dev/ttyACM0'

#mbed = SerialRPC(serdev, 9600)

 ###########################
 #
 #    Global Variables
 #
 ###########################

#Sonar Sensor Readings

global SENREAD_SONAR_FLEFT_READING
global SENREAD_SONAR_FCENTRE_READING
global SENREAD_SONAR_FRIGHT_READING

#RF COMMS
global COMMREAD_RFMESSAGE_LATESTMESSAGE
global COMMREAD_RFMESSAGE_MESSAGEREADY

#Robot Variables
global ROBOT_VARIABLES_CURRENTSPEED
global ROBOT_STOPPING_DISTANCE
global ROBOT_DANGER_DISTANCE
global ROBOT_VARIABLES_CURRENTSPEED

global SEN_LEDSTRUP_PURERED_LOWINTENSITY
global SEN_LEDSTRUP_PUREGREEN_LOWINTENSITY
global SEN_LEDSTRUP_PUREBLUE_LOWINTENSITY

global SEN_LEDSTRUP_PURERED_HIGHINTENSITY
global SEN_LEDSTRUP_PUREGREEN_HIGHINTENSITY
global SEN_LEDSTRUP_PUREBLUE_HIGHINTENSITY

#Set Variables
ROBOT_STOPPING_DISTANCE = 250
ROBOT_DANGER_DISTANCE = 500
ROBOT_VARIABLES_CURRENTSPEED = 0

SEN_LEDSTRUP_PURERED_LOWINTENSITY = ("40","0","0")
SEN_LEDSTRUP_PUREGREEN_LOWINTENSITY = ("0","40","0")
SEN_LEDSTRUP_PUREBLUE_LOWINTENSITY = ("0","0","40")

SEN_LEDSTRUP_PURERED_HIGHINTENSITY = ("255","0","0")
SEN_LEDSTRUP_PUREGREEN_HIGHINTENSITY = ("0","255","0")
SEN_LEDSTRUP_PUREBLUE_HIGHINTENSITY = ("0","0","255")


def SENFUNC_SONAR_getSonarReadings():
	
	global SENREAD_SONAR_FLEFT_READING
	global SENREAD_SONAR_FCENTRE_READING
	global SENREAD_SONAR_FRIGHT_READING
	result = mbed.rpc("getSonar", "run", "")
	split = result.split("#")
	sonarData = split[1]
	SENREAD_SONAR_FLEFT_READING, SENREAD_SONAR_FCENTRE_READING, SENREAD_SONAR_FRIGHT_READING = sonarData.split(",")
	SENREAD_SONAR_FLEFT_READING = int(SENREAD_SONAR_FLEFT_READING)
	SENREAD_SONAR_FCENTRE_READING = int(SENREAD_SONAR_FCENTRE_READING)
	SENREAD_SONAR_FRIGHT_READING = int(SENREAD_SONAR_FRIGHT_READING)


def COMMFUNC_RF_getLatestMessage():
	result = mbed.rpc("getRFMessage", "run", "")
	split = result.split("#")
	messageData = split[1]
	if messageData == "NO_MESSAGES_TO_READ":
		COMMREAD_RFMESSAGE_MESSAGEREADY = False
		print("No Message Available")
	else:
		COMMREAD_RFMESSAGE_LATESTMESSAGE = messageData


def MOVFUNC_SERVODRIVER_CHANGESPEED(speed):
	ROBOT_VARIABLES_CURRENTSPEED = speed
	newSpeed = str(speed)
	result = mbed.rpc("changeSpeed", "run", (newSpeed))
	print("Speed changed ", result)
	

def MOVFUNC_SERVODRIVER_TESTEACHMOTOR():
	result = mbed.rpc("testEachMotor", "run", "")
	
def MOVFUNC_SERVODRIVER_GOFORWARD():
	result = mbed.rpc("goForward", "run", "")
	
def MOVFUNC_SERVODRIVER_GOBACKWARD():
	result = mbed.rpc("goBackward", "run", "")

def MOVFUNC_SERVODRIVER_STEERBACKWARD_RIGHT():
	result = mbed.rpc("steerBackwardRight", "run", "")

def MOVFUNC_SERVODRIVER_STEERBACKWARD_LEFT():
	result = mbed.rpc("steerBackwardLeft", "run", "")

def MOVFUNC_SERVODRIVER_STEERFORWARD_RIGHT():
	result = mbed.rpc("steerForwardRight", "run", "")
	
def MOVFUNC_SERVODRIVER_STEERFORWARD_LEFT():
	result = mbed.rpc("steerForwardLeft", "run", "")

def MOVFUNC_SERVODRIVER_STOPALLWHEELS():
	result = mbed.rpc("stopAllWheels", "run", "")
	
def MOVFUNC_SERVODRIVER_CLEARALLPWM():
	result = mbed.rpc("clearPWMDriver", "run", "")

def ACTFUNC_LEDS_SETBLOCKLEDCOLOUR(colour):
	result = mbed.rpc("setLEDBlockColour", "run", colour)


def ACTFUNC_LEDS_SETDOUBLECOLOUR(colourLeft, colourRight):
	doubleColour = colourLeft + colourRight
	result = mbed.rpc("setLEDDoubleColour", "run", doubleColour)



def BEHFUNC_stateMachine():
	global SENREAD_SONAR_FLEFT_READING
	global SENREAD_SONAR_FCENTRE_READING
	global SENREAD_SONAR_FRIGHT_READING
	global ROBOT_STOPPING_DISTANCE
	global ROBOT_DANGER_DISTANCE
	global SEN_LEDSTRUP_PURERED_LOWINTENSITY
	global SEN_LEDSTRUP_PUREGREEN_LOWINTENSITY
	global SEN_LEDSTRUP_PUREBLUE_LOWINTENSITY
	global SEN_LEDSTRUP_PURERED_HIGHINTENSITY
	global SEN_LEDSTRUP_PUREGREEN_HIGHINTENSITY
	global SEN_LEDSTRUP_PUREBLUE_HIGHINTENSITY
	
	SENFUNC_SONAR_getSonarReadings()

	print(SENREAD_SONAR_FLEFT_READING)
	print(SENREAD_SONAR_FCENTRE_READING)
	print(SENREAD_SONAR_FRIGHT_READING)
	#If too close to object
	if SENREAD_SONAR_FLEFT_READING < ROBOT_STOPPING_DISTANCE or SENREAD_SONAR_FCENTRE_READING < ROBOT_STOPPING_DISTANCE or SENREAD_SONAR_FRIGHT_READING < ROBOT_STOPPING_DISTANCE:
		print("Too Close")
		MOVFUNC_SERVODRIVER_CLEARALLPWM()
		ACTFUNC_LEDS_SETBLOCKLEDCOLOUR(SEN_LEDSTRUP_PURERED_LOWINTENSITY)
		MOVFUNC_SERVODRIVER_CHANGESPEED(0)
		MOVFUNC_SERVODRIVER_GOBACKWARD()
		time.sleep(1)
		#BEHFUNC_reverseHalfSpeed();
		#justreversed = true;
		
		
	#Object to the left
	elif SENREAD_SONAR_FLEFT_READING < ROBOT_DANGER_DISTANCE and SENREAD_SONAR_FCENTRE_READING >= ROBOT_DANGER_DISTANCE and SENREAD_SONAR_FRIGHT_READING >= ROBOT_DANGER_DISTANCE:
		print("Maybe to the left")
		ACTFUNC_LEDS_SETDOUBLECOLOUR(SEN_LEDSTRUP_PUREBLUE_LOWINTENSITY, SEN_LEDSTRUP_PUREGREEN_LOWINTENSITY)
		#if(justreversed){
			#BEHFUNC_turn180();
			#justreversed = false;
		#else:
		MOVFUNC_SERVODRIVER_CHANGESPEED(3)
		MOVFUNC_SERVODRIVER_STEERFORWARD_RIGHT()
		
	#Object to the right
	elif SENREAD_SONAR_FLEFT_READING >= ROBOT_DANGER_DISTANCE and SENREAD_SONAR_FCENTRE_READING >= ROBOT_DANGER_DISTANCE and SENREAD_SONAR_FRIGHT_READING < ROBOT_DANGER_DISTANCE:
		print("maybe to the right")
		ACTFUNC_LEDS_SETDOUBLECOLOUR(SEN_LEDSTRUP_PUREGREEN_LOWINTENSITY, SEN_LEDSTRUP_PUREBLUE_LOWINTENSITY)
		#if(justreversed){
			#BEHFUNC_turn180();
			#justreversed = false;
		#else:
		MOVFUNC_SERVODRIVER_CHANGESPEED(3)
		MOVFUNC_SERVODRIVER_STEERFORWARD_LEFT()
		
		
	#If getting close to object
	elif SENREAD_SONAR_FLEFT_READING < ROBOT_DANGER_DISTANCE or SENREAD_SONAR_FCENTRE_READING < ROBOT_DANGER_DISTANCE or SENREAD_SONAR_FRIGHT_READING < ROBOT_DANGER_DISTANCE:
		print("maybe ahead")
		ACTFUNC_LEDS_SETBLOCKLEDCOLOUR(SEN_LEDSTRUP_PUREBLUE_LOWINTENSITY)
		#if(justreversed){
			#BEHFUNC_turn180();
			#justreversed = false;
		#else:
		MOVFUNC_SERVODRIVER_CHANGESPEED(7)
		MOVFUNC_SERVODRIVER_GOFORWARD()
		
	#If no pbjects detected
	else:
		print("Safe I think")
		ACTFUNC_LEDS_SETBLOCKLEDCOLOUR(SEN_LEDSTRUP_PUREGREEN_LOWINTENSITY)
		MOVFUNC_SERVODRIVER_CHANGESPEED(0)
		MOVFUNC_SERVODRIVER_GOFORWARD()
		

#for i in range(0,10):
	#BEHFUNC_stateMachine()
	#time.sleep(0.5)

while True:
	#BEHFUNC_stateMachine()
	
	a = 1
	
	
	#mbed.ser.close()
